name: TimoSolo
description: Thoughts on Life, the Universe and Everything
url: http://timosolo.me
markdown: kramdown
permalink: /blog/:title
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" 
    values:
      layout: "post"
      author: Timothy Solomon